project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "herdiantrisufriyana.com"
  google-analytics: "G-4KFTWL6MMP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



